plugins {
    id 'minecraft'
}

unimined.minecraft {
//    fabric { // Use fabric loader so mixin extras and other such goodies are automatically included
//         loader gradle.ext.hasProperty('fabric_loader') ? gradle.ext.fabric_loader : '0'
//    }
    defaultRemapJar = false
    runs.off = true
}
