// DO NOT DELETE THIS FILE.
// even if we don't need fabric now, we still may need for someday.
// luoxueyasha 2025.10.25

//plugins {
//    id 'minecraft'
//}
//
//unimined.minecraft {
//    fabric {
//        loader gradle.ext.fabric_loader
//    }
//}
//runClient.javaLauncher = null
//runServer.javaLauncher = null